### ISSUE TITLE
Add a button programmatically

### ISSUE THREAD

**Issue by mshll** [BalestraPatrick/SquishyButton#2]
Seems like adding the button programmatically doesn't work... it shows a white square with the button title only...

**Comment by BalestraPatrick** [comment]
Hey @iiMshl! Could you please share a simple example project or a simple snippet to reproduce the issue?

**Comment by mshll** [comment]
Sure!

> var btnSquish = SquishButton()
    override func viewDidLoad() {
        super.viewDidLoad()
        btnSquish.frame = CGRect(x: view.center.x, y: view.center.y - 100, width: 100, height: 50)
        btnSquish.setTitle("TEST", for: .normal)
        view.addSubview(btnSquish)
    }

![img_34dcff0dcc0e-1](https://user-images.githubusercontent.com/17913113/37057350-14167c3a-2155-11e8-8afc-3bc35fd97cfd.jpeg)

As you can see the second button is made in storyboard but the first is programmatically.

**Comment by BalestraPatrick** [comment]
Hey @iiMshl! I just fixed this issue in the last version 0.2 that I pushed to CocoaPods. Please update your project and the button should now work as expected 👍
